### ISSUE TITLE
serialize Paws::DynamoDB  response data structure seems not stable

### ISSUE THREAD

**Issue by dbaid** [stevecaldwell77/Net-Amazon-DynamoDB-Marshaler#1]
Hello,

   I am trying to unmarshal Paws response hashref, but seems not very stable.
   Here is my testing code.
use strict;
use warnings;
use Paws;
use v5.30;
use Data::Printer;
use Data::Dumper qw(Dumper);
use Net::Amazon::DynamoDB::Marshaler;
my $table_name = 'Emails_7';
$ENV{'AWS_CONFIG_FILE'} = 'C:\Users\p10303550\.aws\credentials';
my $d = Paws->service('DynamoDB',region => 'us-east-2');
my $r;
 $r = $d->Scan(TableName => $table_name);
my $r2=$r->Items->[0]->Map;
print Dumper $r2;

my $attrs = dynamodb_unmarshal($r2);
print Dumper $attrs;

foreach my $col (keys %$attrs) { say "$col : $attrs->{$col}";}
==============================================
My test result:
------test1-------
$VAR1 = {
          'cnt' => bless( {
                            'N' => '45',
                            'L' => []
                          }, 'Paws::DynamoDB::AttributeValue' ),
          'email' => bless( {
                              'L' => [],
                              'S' => 'e2@test.com'
                            }, 'Paws::DynamoDB::AttributeValue' )
        };
$VAR1 = {
          'cnt' => '45',
          'email' => []
        };
cnt : 45
email : ARRAY(0x8ff9278)

------ test2------------
$VAR1 = {
          'cnt' => bless( {
                            'L' => [],
                            'N' => '45'
                          }, 'Paws::DynamoDB::AttributeValue' ),
          'email' => bless( {
                              'L' => [],
                              'S' => 'e2@test.com'
                            }, 'Paws::DynamoDB::AttributeValue' )
        };
$VAR1 = {
          'cnt' => [],
          'email' => []
        };
cnt : ARRAY(0x8d02950)
email : ARRAY(0x8d072a0)

---test3-----------------------------
$VAR1 = {
          'email' => bless( {
                              'S' => 'e2@test.com',
                              'L' => []
                            }, 'Paws::DynamoDB::AttributeValue' ),
          'cnt' => bless( {
                            'L' => [],
                            'N' => '45'
                          }, 'Paws::DynamoDB::AttributeValue' )
        };
$VAR1 = {
          'email' => 'e2@test.com',
          'cnt' => []
        };
email : e2@test.com
cnt : ARRAY(0x8ee8530)

------test4-----------------------
$VAR1 = {
          'email' => bless( {
                              'S' => 'e2@test.com',
                              'L' => []
                            }, 'Paws::DynamoDB::AttributeValue' ),
          'cnt' => bless( {
                            'N' => '45',
                            'L' => []
                          }, 'Paws::DynamoDB::AttributeValue' )
        };
$VAR1 = {
          'cnt' => '45',
          'email' => 'e2@test.com'
        };
cnt : 45
email : e2@test.com

Any suggestions ??

Regards,
Steven

**Comment by stevecaldwell77** [comment]
@dbaid - thanks for reporting this. It appears there is a long-standing bug in Paws where an empty 'L' attribute is included in `Paws::DynamoDB::AttributeValue`, see:

  https://github.com/pplu/aws-sdk-perl/issues/79

Somehow this issue never reared its head for me, but it's showing up for you. I've fixed it in version `0.07` of `Net::Amazon::DynamoDB::Marshaler`, which I just released to CPAN.
